name: macOS ARM

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm]
        include:
          - config: "default"
            install: "brew install cmake tbb fmt boost ninja"
            cmake_opts: ""
          - config: "no_fmt"
            install: "brew install cmake tbb boost ninja"
            cmake_opts: "-DWITH_FMT=OFF"
          - config: "no_tbb"
            install: "brew install cmake fmt boost ninja"
            cmake_opts: "-DWITH_TBB=OFF"
          - config: "no_boost"
            install: "brew install cmake tbb fmt ninja"
            cmake_opts: "-DWITH_BOOST=OFF"
          - config: "no_fmt_no_tbb"
            install: "brew install cmake boost ninja"
            cmake_opts: "-DWITH_FMT=OFF -DWITH_TBB=OFF"
          - config: "no_fmt_no_boost"
            install: "brew install cmake tbb ninja"
            cmake_opts: "-DWITH_FMT=OFF -DWITH_BOOST=OFF"
          - config: "no_tbb_no_boost"
            install: "brew install cmake fmt ninja"
            cmake_opts: "-DWITH_TBB=OFF -DWITH_BOOST=OFF"
          - config: "no_fmt_no_tbb_no_boost"
            install: "brew install cmake ninja"
            cmake_opts: "-DWITH_FMT=OFF -DWITH_TBB=OFF -DWITH_BOOST=OFF"

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Setup Homebrew
      run: |
        which brew
        if [ $? -ne 0 ]; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi

    - name: Install dependencies
      run: ${{ matrix.config.install }}

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1

    - name: Check Clang Version
      run: clang++ --version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.config.cmake_opts }}

    - name: Build
      run: cmake --build build --config Release